import {StyleSheet} from 'react-native';
import { theme } from "../../core/theme";
export default StyleSheet.create({
  placeholder: {
    color: theme.colors.secondary,
  },
  container: {
    marginVertical: 5,
    justifyContent: 'center',
    width: '100%',
  },
  label: {
    paddingLeft: 10,
    paddingBottom: 5,
    color: theme.colors.secondary,
  },
  value: {
    color: theme.colors.onSurface,
  },
  selector: {
    height: 45,
    backgroundColor: theme.colors.background,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingLeft: 15,
    paddingRight: 15,
    borderWidth: 1,
    borderColor: theme.colors.secondary,
    borderRadius: 5,
    width: '100%',
  },
  textItem: {
    color: '#333333',
  },
  piker: {
    position: 'absolute',
    color: 'transparent',
    backgroundColor: 'transparent',
    height: 20,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 15,
    paddingRight: 15,
    bottom: 0,
    width: '100%',
  },
  select: {
    height: 35,
    alignSelf: 'stretch',
    justifyContent: 'center',
    borderColor: '#C7C7C7',
    margin: 10,
    borderWidth: 1,
    borderRadius: 6,
  },
  text: {
    color: theme.colors.onSurface,
    fontFamily: 'Roboto-Medium',
    fontSize: 12,
    marginLeft: 12,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    backgroundColor: 'rgba(57,60,60,0.7)',
  },
  modalView: {
    width: '100%',
    backgroundColor: theme.colors.surface,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    bottom: 0,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  buttonClose: {
    marginLeft: '55%',
    color: '#004883',
    alignItems: 'center',
    marginTop: 8,
    fontSize: 16,
    fontFamily: 'Roboto-Bold',
  },
  buttonLimpiar: {
    color: '#65B3C6',
    alignItems: 'center',
    marginTop: 8,
  },
  clearbtn: {},
  separator: {
    height: 5,
    width: 60,
    marginHorizontal: 50,
    borderWidth: 3,
    marginLeft: '40%',
    borderColor: theme.colors.secondary,
    borderRadius: 10,
  },
  closebtn: {},
  buttonSalir: {
    width: 30,
    height: 30,
    resizeMode: 'contain',
  },
  buttonFilter: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  containerGradient: {
    flexDirection: 'row',
    height: 50,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    marginTop: 20,
    color: theme.colors.onSurface,
    textAlign: 'center',
  },
  titleFilter: {
    color:  theme.colors.onSurface,
    fontSize: 16,
    fontFamily: 'Roboto-Bold',
    textAlign: 'center',
  },
  containHeader: {
    paddingTop: 15,
    marginBottom: 40,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
  },
  content: {
    flexDirection: 'row',
    marginHorizontal: 20,
    alignItems: 'center',
    alignContent: 'center',
  },
  filtros: {
    paddingHorizontal: '5%',
  },
});
